function [MOVINGREG] = registerImages_phaseCorrelation(MOVING,FIXED)
%registerImages_phaseCorrelation  Register grayscale images using phase correlation.
%  [MOVINGREG] = registerImages_phaseCorrelation(MOVING,FIXED) Register grayscale images
%  MOVING and FIXED using phase correlation. The registered image is stored in the
%  structure array MOVINGREG.

% Auto-generated by registrationEstimator app on 14-Jan-2026
%-----------------------------------------------------------

% Observation: don't mask the FIXED image, but for some reason masking the MOVING image is ok


% Normalize FIXED image

% Get linear indices to finite valued data
finiteIdx = isfinite(FIXED(:));

% Replace NaN values with 0
FIXED(isnan(FIXED)) = 0;

% Replace Inf values with 1
FIXED(FIXED==Inf) = 1;

% Replace -Inf values with 0
FIXED(FIXED==-Inf) = 0;

% % Normalize input data to range in [0,1].
% FIXEDmin = min(FIXED(:));
% FIXEDmax = max(FIXED(:));
% if isequal(FIXEDmax,FIXEDmin)
%     FIXED = 0*FIXED;
% else
%     FIXED(finiteIdx) = (FIXED(finiteIdx) - FIXEDmin) ./ (FIXEDmax - FIXEDmin);
% end

% Normalize MOVING image

% Get linear indices to finite valued data
finiteIdx = isfinite(MOVING(:));

% Replace NaN values with 0
MOVING(isnan(MOVING)) = 0;

% Replace Inf values with 1
MOVING(MOVING==Inf) = 1;

% Replace -Inf values with 0
MOVING(MOVING==-Inf) = 0;

% % Normalize input data to range in [0,1].
% MOVINGmin = min(MOVING(:));
% MOVINGmax = max(MOVING(:));
% if isequal(MOVINGmax,MOVINGmin)
%     MOVING = 0*MOVING;
% else
%     MOVING(finiteIdx) = (MOVING(finiteIdx) - MOVINGmin) ./ (MOVINGmax - MOVINGmin);
% end

% Default spatial referencing objects
fixedRefObj = imref2d(size(FIXED));
movingRefObj = imref2d(size(MOVING));

% Phase correlation
tform = imregcorr(MOVING,movingRefObj,FIXED,fixedRefObj,'Method','gradcorr','transformType','rigid');

MOVINGREG.Transformation = tform;
MOVINGREG.RegisteredImage = imwarp(MOVING, movingRefObj, tform, 'OutputView', fixedRefObj, 'SmoothEdges', true, 'Interp', 'cubic');

% Store spatial referencing object
MOVINGREG.SpatialRefObj = fixedRefObj;

end

