function [MOVINGREG] = registerImages_monomodal(MOVING,FIXED,MOVINGREG,WEIGHTS)
%registerImages  Register grayscale images using auto-generated code from Registration Estimator app.
%  [MOVINGREG] = registerImages(MOVING,FIXED) Register grayscale images
%  MOVING and FIXED using auto-generated code from the Registration
%  Estimator app. The values for all registration parameters were set
%  interactively in the app and result in the registered image stored in the
%  structure array MOVINGREG.


% Auto-generated by registrationEstimator app on 14-Jan-2026
%-----------------------------------------------------------

% Observation: don't mask the FIXED image, but for some reason masking the MOVING image is ok


% Normalize FIXED image

% Get linear indices to finite valued data
finiteIdx = isfinite(FIXED(:));

% Replace NaN values with 0
FIXED(isnan(FIXED)) = 0;

% Replace Inf values with 1
FIXED(FIXED==Inf) = 1;

% Replace -Inf values with 0
FIXED(FIXED==-Inf) = 0;

% % Normalize input data to range in [0,1].
% FIXEDmin = min(FIXED(:));
% FIXEDmax = max(FIXED(:));
% if isequal(FIXEDmax,FIXEDmin)
%     FIXED = 0*FIXED;
% else
%     FIXED(finiteIdx) = (FIXED(finiteIdx) - FIXEDmin) ./ (FIXEDmax - FIXEDmin);
% end

% Normalize MOVING image

% Get linear indices to finite valued data
finiteIdx = isfinite(MOVING(:));

% Replace NaN values with 0
MOVING(isnan(MOVING)) = 0;

% Replace Inf values with 1
MOVING(MOVING==Inf) = 1;

% Replace -Inf values with 0
MOVING(MOVING==-Inf) = 0;

% % Normalize input data to range in [0,1].
% MOVINGmin = min(MOVING(:));
% MOVINGmax = max(MOVING(:));
% if isequal(MOVINGmax,MOVINGmin)
%     MOVING = 0*MOVING;
% else
%     MOVING(finiteIdx) = (MOVING(finiteIdx) - MOVINGmin) ./ (MOVINGmax - MOVINGmin);
% end

% Default spatial referencing objects
fixedRefObj = imref2d(size(FIXED));
movingRefObj = imref2d(size(MOVING));

% Intensity-based registration
[optimizer, metric] = imregconfig('monomodal');
optimizer.GradientMagnitudeTolerance = 1.00000e-04;
optimizer.MinimumStepLength = 1.00000e-05;
optimizer.MaximumStepLength = 6.25000e-02;
optimizer.MaximumIterations = 100;
optimizer.RelaxationFactor = 0.500000;

% Determine initial transformation
% Use MOVINGREG transformation if provided, otherwise use center alignment
if nargin >= 3 && ~isempty(MOVINGREG) && isfield(MOVINGREG,'Transformation') && ~isempty(MOVINGREG.Transformation)
    % Use transformation from phase correlation as starting point
    initTform = MOVINGREG.Transformation;
else
    % Align centers (fallback if MOVINGREG not provided)
    fixedCenterXWorld = mean(fixedRefObj.XWorldLimits);
    fixedCenterYWorld = mean(fixedRefObj.YWorldLimits);
    movingCenterXWorld = mean(movingRefObj.XWorldLimits);
    movingCenterYWorld = mean(movingRefObj.YWorldLimits);
    translationX = fixedCenterXWorld - movingCenterXWorld;
    translationY = fixedCenterYWorld - movingCenterYWorld;
    
    % Coarse alignment
    initTform = affinetform2d();
    initTform.A(1:2,3) = [translationX ; translationY];
end


% Registration without weights
tform = imregtform(MOVING,movingRefObj,FIXED,fixedRefObj,'rigid',optimizer,metric,'PyramidLevels',3,'InitialTransformation',initTform);
MOVINGREG.Transformation = tform;
MOVINGREG.RegisteredImage = imwarp(MOVING, movingRefObj, tform, 'OutputView', fixedRefObj, 'SmoothEdges', true, 'Interp', 'cubic');

% Store spatial referencing object
MOVINGREG.SpatialRefObj = fixedRefObj;

end

% Helper function for weighted registration cost
function cost = weightedRegistrationCost(params, MOVING, FIXED, movingRefObj, fixedRefObj, WEIGHTS)
    % params: [tx, ty, rotation_angle]
    % Construct rigid transformation
    tform = affinetform2d();
    theta = params(3);
    tform.A = [cos(theta) -sin(theta) params(1);
               sin(theta)  cos(theta) params(2);
               0           0           1];
    
    % Warp moving image
    MOVING_warped = imwarp(MOVING, movingRefObj, tform, 'OutputView', fixedRefObj, 'SmoothEdges', true, 'Interp', 'cubic');
    
    % Compute weighted mean squared error
    diff = (MOVING_warped - FIXED).^2;
    cost = sum(diff(:) .* WEIGHTS(:)) / sum(WEIGHTS(:));
end
